### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by mark2185** [jwoglom/signal-curses#1]
The requirements are missing the "gi" module which is (I presume) the `vext.gi` module.

Even after installing that, main.py says `ModuleNotFoundError: No module named 'secret'`

Which module is that? Considering the `from secret import SELF_PHONE, TO_PHONE` statement, I'm guessing it's not in pip repositories?

**Comment by jwoglom** [comment]
The "gi" module refers to pygobject, which isn't in pip -- [you'll need to install it using a package manager](https://pygobject.readthedocs.io/en/latest/). This is an already-needed dependency of pydbus, see 'Requirements' at https://github.com/LEW21/pydbus/blob/master/README.rst

The "secret" import is something I had in place only for debugging; I placed a "secret.py" file defining those two constants. This is no longer needed and I just removed it.

**Comment by jwoglom** [comment]
I've updated README.md with some more specifics, let me know if you think there should be more detail there.
