### ISSUE TITLE
Unrecognized arguments '--json'

### ISSUE THREAD

**Issue by mark2185** [jwoglom/signal-curses#2]
I registered my device on signal-cli and started the `signal-cli -u +12345678 daemon`, and after starting `python main.py -u +12345678` it states `signal-cli: error: unrecognized arguments: '--json'` over the interface.

![image](https://user-images.githubusercontent.com/8365241/43077711-97778f60-8e88-11e8-952c-49bfb4f6e56a.png)

If I resize the terminal, it redraws and the message is gone, but my contacts and groups are still empty. Am I missing something?

**Comment by jwoglom** [comment]
Make sure you're using signal-cli version >=0.6.0, which introduced json output. If you were using a version from your package manager, uninstall it and use the installation instructions in the readme with VERSION=0.6.0

https://github.com/AsamK/signal-cli/blob/master/README.md

**Comment by mark2185** [comment]
I installed it from AUR and pacman states the version is 0.6.0-1.

**Comment by jwoglom** [comment]
signal-curses manages its own signal-cli daemon so you shouldn't run your own at the same time -- hopefully this fixes at least part of your problem.

I'd eventually like to separate signal-curses from needing to manage the daemon itself -- it uses the json output of the daemon to read the data off of stdout -- and have it use the system/user bus directly, but I don't have a working version of that yet.

**Comment by mark2185** [comment]
I deleted signal-cli from AUR, deleted the config, and built the latest version from git using gradle.

Then I _copied_ the binary (because if I symlinked it, signal-curses complained there were too many levels of linking) to /usr/local/bin/, but now it states `Could not find or load main class  org.asamk.signal.Main` and throws an exception.

![image](https://user-images.githubusercontent.com/8365241/43124686-20cfcd6e-8f28-11e8-914c-8b875f2a494a.png)

**Comment by jwoglom** [comment]
Looks like you're running into https://github.com/AsamK/signal-cli/issues/25

The main class error is coming from signal-cli.

Also, you can try `tail -f`-ing sc.log from wherever you're running signal-curses if you want to see debug and error information. Error handling doesn't display very well when curses is displaying a UI on the screen, as you can probably see.
