### ISSUE TITLE
unrecognized arguments json again

### ISSUE THREAD

**Issue by luxpir** [jwoglom/signal-curses#3]
Was going to delete this as a duplicate, but instead re-opened because I can't get around the issue with the fixes put forward in the other closed issue.

Installed with pip3 and run with python3, QR code accepted etc. and all fine, but if I open signal-curses via python3 main.py -u [+num] I get the above error and after 30-60s a popup about being unable to connect to system bus.

I tried the dbus instructions from system-cli docs but that didn't do it. So what other options are there at this point?

My understanding of the dbus system is minimal!

**Comment by luxpir** [comment]
delete me

**Comment by riazm** [comment]
My sc.log says 
`2018-10-01 09:22:19 args Namespace(bus='session', configDir='/home/r/.config/signal', phone='+redacted')
2018-10-01 09:22:19 noContacts!
2018-10-01 09:22:19 main None
2018-10-01 09:22:19 daemon thread
2018-10-01 09:22:19 message thread
2018-10-01 09:22:19 contacts:  0
2018-10-01 09:22:19 daemon popen
2018-10-01 09:22:19 start forms {'MAIN': <__main__.SelectForm object at 0x7f06bc0df978>, 'APP': <__main__.AppForm object at 0x7f06bc0dfd30>}
2018-10-01 09:22:21 EXCEPTION in daemon Command 'None' returned non-zero exit status 1.
2018-10-01 09:22:21 daemon exit
2018-10-01 09:22:28 2
2018-10-01 09:22:28 None
2018-10-01 09:22:30 mloop forms {'MAIN': <__main__.SelectForm object at 0x7f06bc0df978>, 'APP': <__main__.AppForm object at 0x7f06bc0dfd30>}
2018-10-01 09:22:33 SIGINT
`

**Comment by riazm** [comment]
SAD that this doesn't work so I'm doing some digging.
```
r@belatinous:~/signal-curses$ signal-cli -v
signal-cli 0.6.0
r@belatinous:~/signal-curses$ signal-cli -u +[REDACTED] --json
usage: signal-cli [-h] [-v] [--config CONFIG] [-u USERNAME | --dbus | --dbus-system]
                  {link,addDevice,listDevices,removeDevice,register,unregister,updateAccount,setPin,removePin,verify,send,quitGroup,updateGroup,listGroups,listIdentities,trust,receive,daemon}
                  ...
signal-cli: error: unrecognized arguments: '--json'

Did you mean:
        --version
```

Which seems odd? I think I have version 0.6.0 but it doesn't support json? curious

**Comment by riazm** [comment]
Yes @jwoglom building manually has got me around this issue, perhaps you could update the docs to say that you need the latest build of signal-cli (which still reports its build version as 0.6.0, but is not)

**Comment by jwoglom** [comment]
https://github.com/jwoglom/signal-curses/commit/b93a112b8e17cb83161f22b7e85b629cabb4d4b3

**Comment by riazm** [comment]
for the record, you no longer need to build signal-cli from source the packaged releases work fine.
